FROM busybox

RUN mkdir import

COPY import/keycloak-themes/ import/themes
COPY import/realm-config/pre-prod/catenax-central/ import/catenax-central/realms
COPY import/realm-config/pre-prod/catenax-shared/ import/catenax-shared/realms
